name: Build & Deploy Gatsby to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      NODE_OPTIONS: --openssl-legacy-provider

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node (20) and cache
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "yarn"

      - name: Enable Corepack (so Yarn releases in packageManager work)
        run: |
          corepack enable || true
          # try to prepare the stable Yarn so 'yarn' exists; ignore failures
          corepack prepare yarn@stable --activate || true
          echo "Corepack enabled. node: $(node -v), npm: $(npm -v), yarn: $(yarn --version 2>/dev/null || echo 'not installed')"

      - name: Configure Pages (prepare Pages environment)
        id: pages
        uses: actions/configure-pages@v5
        with:
          static_site_generator: gatsby

      - name: Install dependencies (Yarn v4 / Yarn v1 / npm fallback)
        run: |
          set -euo pipefail
          echo "Files present:"
          [ -f yarn.lock ] && echo "- yarn.lock exists" || echo "- yarn.lock missing"
          [ -f package-lock.json ] && echo "- package-lock.json exists" || echo "- package-lock.json missing"

          if [ -f yarn.lock ]; then
            # If yarn is available and is v4 (berry), use immutable install.
            if command -v yarn >/dev/null 2>&1 && yarn --version | grep -q '^[4-]'; then
              echo "Detected Yarn v4 (berry) -> running immutable install"
              yarn install --immutable --inline-builds
            else
              # If yarn is not v4, install Yarn v1 and use frozen-lockfile (safer for older projects)
              echo "Installing Yarn v1 (fallback) to honor yarn.lock"
              npm install -g yarn@1.22.22
              yarn --version
              yarn install --frozen-lockfile --network-concurrency 1 || yarn install --network-concurrency 1
            fi
          elif [ -f package-lock.json ]; then
            echo "package-lock.json found -> using npm ci"
            npm ci
          else
            echo "No lockfile found -> using npm install"
            npm install
          fi
        timeout-minutes: 30

      - name: Build Gatsby site
        run: |
          echo "Building with Gatsby..."
          # Prefer yarn if it exists, else npm
          if command -v yarn >/dev/null 2>&1; then
            yarn build
          else
            npm run build
          fi
        timeout-minutes: 20

      - name: Upload pages artifact (public)
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
