name: Build & Deploy Gatsby to GitHub Pages

# Run on pushes to the main branch (change 'main' if your branch name differs)
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      # Protect against OpenSSL/webpack crypto errors on older build stacks
      NODE_OPTIONS: --openssl-legacy-provider

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js (Node 20 required by some transitive deps)
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Ensure Yarn v1 (project expects yarn v1.x)
        run: npm install -g yarn@1.22.22

      - name: Install dependencies (use frozen lockfile if present)
        shell: bash
        run: |
          if [ -f yarn.lock ]; then
            echo "Using yarn.lock => installing with frozen lockfile"
            yarn install --frozen-lockfile
          else
            echo "No yarn.lock => normal install"
            yarn install
          fi

      - name: Build site
        # NODE_OPTIONS is inherited from env above; explicit fallback included
        run: |
          echo "Building Gatsby site..."
          yarn build

      - name: Deploy to GitHub Pages (publish ./public -> gh-pages)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          # publish_branch: gh-pages   # default is gh-pages; change if you want another branch
